# Generated by Django 4.1 on 2022-08-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='text',
            new_name='summary',
        ),
    ]
